### ISSUE TITLE
PNG encoding / decoding not available?

### ISSUE THREAD

**Issue by whazzup** [Crigges/Prebuild-LGPL-2.1-FFmpeg-with-OpenH264#1]
Hi, thanks for the work! 
However, can I ask why png encoding / decoding are not available? Would have thought that's under a pretty permissive license.

**Comment by Crigges** [comment]
You are right, zlib is available under a BSD style license, so it would be compatible with the LGPL. However I guess there are quite some free non-GPL libraries which are not included in this build like libvpx or libjpeg.

If you just need png support, then you can try to build FFmpeg on your own with -enable-zlib which completely defies the purpose of the project. And generally speaking it is a good Idea to add more compatible libraries to make this project more useful. So I will try to include zlib support into a new build when I find some time. No promise on the time schedule here

**Comment by whazzup** [comment]
Man if you can find the time that will be awesome! 

We attempted a LGPL build some time ago, but wow, it's not a trivial task...and nope didn't succeed. Like you mentioned, the documentation is definitely not up to date....

**Comment by Crigges** [comment]
Just an update regarding my progress.   
To reprocude the error we can use the command:
`ffmpeg -r 1/5 -i someimage.png -c:v h264 -vf fps=25 -pix_fmt yuv420p out.mp4`
  
I was able to cross compile zlib for 64bit windows with gcc as shared library. Could you check if the license allows static linking? So no addional dll would be required.

A first test configure of ffmpeg with --enable-zlib looks fine so far, but I had no time to run make yet.

**Comment by Crigges** [comment]
I just added a new [release ](https://github.com/Crigges/Prebuilt-LGPL-2.1-FFmpeg-with-OpenH264/releases/tag/v0.1) that comes with zlib and should enable png support.

**Comment by Crigges** [comment]
Gonna close this for now if you still have trouble feel free to reopen
